### ISSUE TITLE
nullnull子怎么去英国了

### ISSUE THREAD

**Issue by Tohrusky** [NULL204/giffgaff-apn-setting#1]

**Comment by NULL204** [comment]
/(ㄒoㄒ)/~~
只是把自己的东西都上传想凑点活跃度，我的LSPosed内测说我GitHub账号不符合要求
这些参数都是魅族工程师发给我的

**Comment by Tohrusky** [comment]
懒 有没有兴趣来我们 压制组玩 里面都是老熟人 大宝啥的
https://github.com/TensoRaws

**Comment by NULL204** [comment]
好呀好呀，但是我很菜的，做不了啥贡献🥹

**Comment by Tohrusky** [comment]
> 好呀好呀，但是我很菜的，做不了啥贡献🥹

加群来聊聊

**Comment by NULL204** [comment]
已经加啦
